# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
