# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171105_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpotifyUser',
        ),
    ]
